### ISSUE TITLE
Rakefile

### ISSUE THREAD

**Issue by xambroz** [fizx/robots#5]
Hello ,
please would you consider including patch to the Rakefile as suggested by Mamoru Tasaka?
https://bugzilla.redhat.com/show_bug.cgi?id=632912

$ diff -u Rakefile.debug Rakefile
--- Rakefile.debug 1970-01-01 09:00:00.000000000 +0900
+++ Rakefile 2010-09-13 02:32:52.000000000 +0900
@@ -21,7 +21,7 @@
 require 'rake/testtask'
 Rake::TestTask.new(:test) do |test|
   test.libs << 'lib' << 'test'
-  test.pattern = 'test/*_/__test.rb'
-  test.pattern = 'test/*_/test__.rb'
  test.verbose = true
  end

@@ -38,7 +38,7 @@
   end
 end

-task :test => :check_dependencies
+#task :test => :check_dependencies

 task :default => :test

**Comment by fizx** [comment]
Applied for 0.10.1

**Comment by xambroz** [comment]
Thank you
